  
version: '3.7'
services:
  nginx_test:
    build: ./nginx
    container_name: nginx_test
    restart: always
    ports:
      - 80:80
      - 5000:5000
    depends_on:
      - pgadmin_test
    networks:
       - postgres

  postgres_test:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
    volumes:
       - db_volume:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin_test:
    image: dpage/pgadmin4
    restart: always
    depends_on:
    - postgres_test
    expose:
    - 80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    tty: true
    networks:
      - postgres

volumes:
  db_volume:
    # driver: local
    # driver_opts:
    #     o: bind
    #     type: none
    #     device: /db_volume

networks:
  postgres:
    driver: bridge